<?php

namespace Tests\Feature;

use App\Services\CryptoService;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

class CryptoTest extends TestCase
{

    private $cryptoService;
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->cryptoService = $this->createMock(CryptoService::class);
    }

    /**
     * A basic feature test example.
     */
    public function test_example(): void
    {
        $response = $this->get('/');
        $response->assertStatus(200);
    }

    public function test_crypto_service(): void {
        $cryptoServiceClass = new CryptoService($this->cryptoService);
        $cryptoServiceClass->getCryptoTickers();
        $this->assertTrue(true);
    }

    public function test_crypto_service_db_tickers(): void {
        $cryptoServiceClass = new CryptoService($this->cryptoService);
        $data = $cryptoServiceClass->getTickers();
        $this->assertTrue(true);
    }
}
